version: '3.6'

services:
  db:
    image: 'postgres:latest'
    restart: 'always'
    environment:
      POSTGRES_USER: 'authservice'
      POSTGRES_PASSWORD: 'secret'
      POSTGRES_DB: 'authservice'
    ports:
      - 5433:5432

  redis:
    image: 'redis:latest'
    ports:
      - 6379:6379
